### PR TITLE
Updated code and added reload command

### PR DESCRIPTION
**Pull request by DuncanCarr**
Changed code to be better by making it follow standard Java conventions, and just generally improving it's iinteractions.

I also added a /messages command, which reloads the configuration file seemlessly, without having to fully stop and restart the server for changes to take effect.

### CODE REVIEW

**Comment by garsh1** [comment]
Alright thanks man, I am still new to plugin development and I haven’t quite worked everything out yet.

**Comment by DuncanCarr** [comment]
> Alright thanks man, I am still new to plugin development and I haven’t quite worked everything out yet.

That's alright. If you are going to use my code, please add me as an author on your Spigot resource, and I would suggest recompiling and updating the resource as well.

**Comment by garsh1** [comment]
I will add you and recompile it tomorrow as soon as I get a chance.

**Comment by garsh1** [comment]
I have recompiled it and added you as a contributor on spigot. I am going to run some tests on it and then update it on spigot.

**Comment by garsh1** [comment]
A problem I have, the message sends along with the default and the first join even if it isn't my first time joining.

**Comment by DuncanCarr** [comment]
There was an if statement checking that. I set it up so that the join message sends regardless, and the first join message is a little addition if you want it. This is the same way that Essentials / EssentialsX is setup, so I assumed you would want it the same way.

I created a new pull request that sets the join and leave messages instead of just sending a message in addition. Now, the join and leave messages will be the ones set in the config.yml, and nothing will send if they are disabled. Your code additions were poorly created and caused some issues on my end. If you have bugs or things you want to be solved, just ask me. I am more than capable of doing it.

**Pull request merged**
